src/Web/Areas/Admin/Models/GenreViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web.Areas.Admin.Models
{
    public class GenreViewModel
    {
        public int Id { get; set; }
        public string GenreName { get; set; }
    }
}

src/Web/Areas/Admin/Controllers/GenreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ApplicationCore.Entities;
using ApplicationCore.Interfaces;
using Web.Areas.Admin.Models;
using Web.Interfaces;
using Microsoft.AspNetCore.Authorization;

// DİKKAT!!!!! CSHTML'lerin içinde Entity'leri mi kullanmalıyız, ViewModel'leri oluşturup onları mı kullanmalıyız? ViewModel'leri kullanacaksak WEB tarafında IGenreViewModelService adında bir servis açılmalı.
// HomeViewModelService(Index için göstermelik veri gönderiyor) ile CartViewModelService'in(Create-Update-Delete işlerini Application Core'daki CartService yardımı ile yapıyor)  
namespace Web.Areas.Admin.Controllers
{
    [Area("Admin"), Authorize(Roles = "admin")]
    public class GenreController : Controller
    {
        private readonly IGenreService _genreService;
        private readonly IGenreViewModelService _genreViewModelService;

        public GenreController(IGenreService genreService, IGenreViewModelService genreViewModelService)
        {
            _genreService = genreService;
            _genreViewModelService = genreViewModelService;
        }

        // GET: Admin/Genres
        public async Task<IActionResult> Index()
        {
            return View(await _genreService.GetAllGenresAsync());
        }

        // GET: Admin/Genres/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Genres/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GenreName")] GenreViewModel genre)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _genreService.AddGenreAsync(genre.GenreName);
                }
                catch (ArgumentException ex)
                {
                    ViewBag.Message = ex.Message;
                    return View(genre);
                }
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        // GET: Admin/Genres/Edit/5
        public async Task<IActionResult> Edit(int genreId)
        {
            Genre genre;
            GenreViewModel vm;
            try
            {
                genre = await _genreService.GetGenreByIdAsync(genreId);
                vm = await _genreViewModelService.GetGenreViewModelAsync(genre);
            }
            catch (ArgumentException ex)
            {
                TempData["Message"] = ex.Message;
                return RedirectToAction(nameof(Index));
            }
            return View(vm);
        }

        // POST: Admin/Genres/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("GenreName,Id")] GenreViewModel vm)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _genreService.UpdateGenreAsync(vm.Id, vm.GenreName);
                }
                catch (ArgumentException ex)
                {
                    ViewBag.Message = ex.Message;
                    return View(vm);
                }
                return RedirectToAction(nameof(Index));
            }
            return View(vm);
        }

        // POST: Admin/Genres/Delete/5
        public async Task<IActionResult> Delete(int genreId)
        {
            try
            {
                await _genreService.DeleteGenreAsync(genreId);
            }
            catch (ArgumentException ex)
            {
                TempData["Message"] = ex.Message;
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

src/Web/Areas/Admin/Views/Genre/Create.cshtml
@model GenreViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Genre</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="GenreName" class="control-label"></label>
                <input asp-for="GenreName" class="form-control" />
                <span asp-validation-for="GenreName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    @if (!string.IsNullOrEmpty(ViewBag.Message))
    {
        <script type="text/javascript">
		alert("@ViewBag.Message");
        </script>
    }
}

src/Web/Areas/Admin/Views/Genre/Edit.cshtml
@model GenreViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Genre</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="GenreName" class="control-label"></label>
                <input asp-for="GenreName" class="form-control" />
                <span asp-validation-for="GenreName" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    @if (!string.IsNullOrEmpty(ViewBag.Message))
    {
        <script type="text/javascript">
		alert("@ViewBag.Message");
        </script>
    }
}

src/Web/Areas/Admin/Views/Genre/Index.cshtml
@model List<Genre>

@{
    ViewData["Title"] = "Index";
}

<h1>Genres Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table table-admin">
    <thead>
        <tr>
            <th>
                Genre Name
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.GenreName
                </td>
                <td>
                    <form class="d-inline-block ms-auto" asp-controller="Genre" asp-action="Delete" method="post" onsubmit="return confirm('Are you sure to delete this item?');">
                        <input type="hidden" name="genreId" value="@item.Id" />
                        <button class="btn btn-danger">Delete</button>
                    </form>
                    <a asp-controller="Genre" asp-action="Edit" asp-route-genreId="@item.Id" class="btn btn-warning">Edit</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts {
    @if (TempData["Message"] != null)
    {
        <script type="text/javascript">
            alert('@TempData["Message"].ToString()');
        </script>
    }
}