src/Web/Areas/Admin/Models/KeyViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web.Areas.Admin.Models
{
    public class KeyViewModel
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public Guid KeyCode { get; set; }
    }
}

src/Web/Areas/Admin/Controllers/KeyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ApplicationCore.Entities;
using Infrastructure.Data;
using ApplicationCore.Interfaces;
using Web.Interfaces;
using Web.Areas.Admin.Models;
using Microsoft.AspNetCore.Authorization;

namespace Web.Areas.Admin.Controllers
{
    [Area("Admin"), Authorize(Roles = "admin")]
    public class KeyController : Controller
    {
        private readonly IKeyService _keyService;
        private readonly IKeyViewModelService _keyViewModelService;

        public KeyController(IKeyService keyService, IKeyViewModelService keyViewModelService)
        {
            _keyService = keyService;
            _keyViewModelService = keyViewModelService;
        }

        // GET: Admin/Key
        public async Task<IActionResult> Index(int productId)
        {
            IndexKeyViewModel vm;
            try
            {
                vm = await _keyViewModelService.GetAllKeysWithViewModel(productId);
            }
            catch (ArgumentException ex)
            {
                ViewBag.Message = ex.Message;
                return NotFound(ex.Message);
            }
            return View(vm);
        }

        //GET: Admin/Key/Create
        public async Task<IActionResult> Create(int productId)
        {
            var vm = new KeyViewModel() { ProductId = productId };
            return View(vm);
        }

        // POST: Admin/Key/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(KeyViewModel vm)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _keyViewModelService.CreateKeyFromViewModelAsync(vm);
                }
                catch (ArgumentException ex)
                {
                    ViewBag.Message = ex.Message;
                    return View(vm);
                }
                return RedirectToAction("Index", new { productId = vm.ProductId });
            }
            return View(vm);
        }

        // GET: Admin/Key/Edit/5
        public async Task<IActionResult> Edit(int keyId)
        {
            KeyViewModel vm;
            try
            {
                vm = await _keyViewModelService.GetKeyEditViewModelAsync(keyId);
            }
            catch (ArgumentException ex)
            {
                return NotFound(ex.Message);
            }
            return View(vm);
        }

        // POST: Admin/Key/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(KeyViewModel vm)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _keyViewModelService.UpdateKeyFromViewModelAsync(vm);
                }
                catch (ArgumentException ex)
                {
                    ViewBag.Message = ex.Message;
                    return View(vm);
                }
                return RedirectToAction("Index", new { productId = vm.ProductId });
            }

            return View(vm);
        }

        // GET: Admin/Key/Delete/5
        public async Task<IActionResult> Delete(int keyId, int productId)
        {
            try
            {
                await _keyService.DeleteKeyAsync(keyId);
            }
            catch (ArgumentException ex)
            {
                TempData["Message"] = ex.Message;
                return RedirectToAction("Index", new { productId = productId });
            }
            return RedirectToAction("Index", new { productId = productId });
        }
    }
}

src/Web/Areas/Admin/Views/Key/Create.cshtml
@model KeyViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Key</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="KeyCode" class="control-label">Key Code</label>
                <input asp-for="KeyCode" class="form-control" />
                <span asp-validation-for="KeyCode" class="text-danger"></span>
            </div>
            <input type="hidden" name="productId" value="@Model.ProductId" />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-route-productId="@Model.ProductId">Back to List</a>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    @if (!string.IsNullOrEmpty(ViewBag.Message))
    {
        <script type="text/javascript">
		alert("@ViewBag.Message");
        </script>
    }
}

src/Web/Areas/Admin/Views/Key/Edit.cshtml
@model KeyViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Key</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="KeyCode" class="control-label">Key Code</label>
                <input asp-for="KeyCode" class="form-control" />
                <span asp-validation-for="KeyCode" class="text-danger"></span>
            </div>
            <input type="hidden" name="Id" value="@Model.Id" />
            <input type="hidden" name="ProductId" value="@Model.ProductId" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-route-productId="@Model.ProductId">Back to List</a>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    @if (!string.IsNullOrEmpty(ViewBag.Message))
    {
        <script type="text/javascript">
		    alert("@ViewBag.Message");
        </script>
    }
}

src/Web/Areas/Admin/Views/Key/Index.cshtml
@model IndexKeyViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
<h3>@Model.PlatformName</h3>
<h3>@Model.GameName</h3>
<p>
    <a asp-action="Create" asp-route-productId="@Model.ProductId">Create New</a>
</p>
<table id="keyTable" class="table table-admin table-bordered table-striped w-100">
    <thead>
        <tr>
            <th>
                Key Code
            </th>
            <th>
                Is Key Valid
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Keys)
        {
            <tr>
                <td>
                    @item.KeyCode
                </td>
                <td>
                    @item.Status
                </td>
                <td>
                    <form class="d-inline-block ms-auto" asp-controller="Key" asp-action="Delete" method="post" onsubmit="return confirm('Are you sure to delete this item?');">
                        <input type="hidden" name="keyId" value="@item.Id" />
                        <input type="hidden" name="productId" value="@Model.ProductId" />
                        <button class="btn btn-danger">Delete</button>
                    </form>
                    <a asp-controller="Key" asp-action="Edit" asp-route-keyId="@item.Id" class="btn btn-warning">Edit</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts{
    <script>
        $("#keyTable").DataTable();
    </script>
    @if (!string.IsNullOrEmpty(ViewBag.Message))
    {
        <script type="text/javascript">
		alert("@ViewBag.Message");
        </script>
    }
    @if (TempData["Message"] != null)
    {
        <script type="text/javascript">
            alert('@TempData["Message"].ToString()');
        </script>
    }
}